### ISSUE TITLE
Rustscan crash with failed memory allocation

### ISSUE THREAD

**Issue by Its-Just-Nans** [RustScan/RustScan#523] opened 2023-07-09 06:46 UTC
**Describe the bug**
Rustscan crash with failed memory allocation

**To Reproduce**
```
rustscan -a 10.0.0.0/10 --ulimit 5000
```

Note that with lower mask value it doesn't crash (limit for me is `/13`)

**Expected behavior**
Maybe display a cleaner error like "Cannot scan this many addresses."

**Screenshots**
![image](https://github.com/RustScan/RustScan/assets/56606507/70f0c8b7-5974-4d86-851b-9ee77f08a319)

**Desktop (please complete the following information):**
- rustscan 2.1.1 (from nix)

**Comment by Oreeeee** [comment] 2023-07-10 11:12
Duplicate of #447

Seems like the tool is trying to extract the CIDR notation into individual IPs and add them to an array, but this takes a lot of RAM.

**Closed** 2024-04-07 07:10 UTC
