### ISSUE TITLE
Rustscan missing ports, even with big timeout

### ISSUE THREAD

**Issue by Kiblyn11** [RustScan/RustScan#125] opened 2020-08-05 19:54 UTC
**Describe the bug**
Rustcan is missing open ports (80 sometimes and 443 all the times for hackerone.com for instance)
Nmap doesn't

**To Reproduce**

Using hackerone.com for the test

```
host hackerone.com
hackerone.com has address 104.16.100.52
hackerone.com has address 104.16.99.52
....
```

```
nmap -p80,443 104.16.99.52 -sV                                             
Starting Nmap 7.80 ( https://nmap.org ) at 2020-08-05 21:45 CEST          
Nmap scan report for 104.16.99.52                                            
Host is up (0.025s latency).                                                 
                                                                             
PORT    STATE SERVICE   VERSION                                              
80/tcp  open  http      cloudflare                                           
443/tcp open  ssl/https cloudflare                                           
2 services unrecognized despite returning data. If you know the service/version, please submit the following fingerprints at https://nmap.org/cgi-bin/subm
it.cgi?new-service :                                                                                                                                      
==============NEXT SERVICE FINGERPRINT (SUBMIT INDIVIDUALLY)==============
SF-Port80-TCP:V=7.80%I=7%D=8/5%Time=5F2B0C5D%P=x86
...
```

```
rustscan -b 500 -t 10000 104.16.99.52

     _____           _    _____
    |  __ \         | |  / ____|
    | |__) |   _ ___| |_| (___   ___ __ _ _ __
    |  _  / | | / __| __|\___ \ / __/ _` | '_ \
    | | \ \ |_| \__ \ |_ ____) | (_| (_| | | | |
    |_|  \_\__,_|___/\__|_____/ \___\__,_|_| |_|
    Faster nmap scanning with rust.

The config file is expected to be at "/home/bob/.config/rustscan/config.toml"

Your file descriptor limit is higher than the batch size. You can potentially increase the speed by increasing the batch size, but this may cause harm to sensitive servers. Your limit is 1024, try batch size 1023.

The batch size is 500

Scanning ports from 104.16.99.52

Open 80
Open 2052
Open 2053
...
```

**Expected behavior**
Report of port 80 and 443 open

**Context**
rustscan v1.6.0

**Comment by brandonskerritt** [comment] 2020-08-05 19:59
I can't repro, even if I do make it more likely to miss ports (15k+ batch size). 

However! That doesn't make this concern any less valid. @bernardoamc is working on IP stuff all this week, and accuracy is one of the things we're working on :) Rest assured, this should be fixed v/ soon :stuck_out_tongue_closed_eyes: 

I'll leave this open and when we make it more likely to succeed, we'll come back and ask you to try again as I can't reproduce :)

**Comment by Kiblyn11** [comment] 2020-08-05 20:01
Great thanks :+1:

**Comment by bernardoamc** [comment] 2020-08-06 01:45
The randomized IP scanning might fix some of those issues, but I will investigate this more carefully. 👍

**Comment by Kiblyn11** [comment] 2020-08-06 06:11
As you told me you cannot reproduce, I tried to find out why.
I think I found out why, I use a VPN to scan, when not on the VPN it works great.
Maybe there is an issue with cloudflare when on a VPN ? ( as it is working with nmap)

**Comment by bernardoamc** [comment] 2020-08-09 17:54
Interesting, thanks for letting us know @Kiblyn11 👍 

Can you try again with the current version? A few performance issues were tackled on the current version that might change things.

**Comment by Kiblyn11** [comment] 2020-08-12 12:06
Thanks for the update, I tried again with version 1.7.1 and it's still missing 443 while in VPN while nmap get it.

**Comment by h3105** [comment] 2020-08-16 09:10
@bernardoamc I can can confirm the issue @Kiblyn11 is having. Especially over OpenVPN rustscan often skips even basic ports (like port 21) making it extremely unreliable.

**Comment by bernardoamc** [comment] 2020-08-16 14:29
We might be overwhelming the host or network. Thanks for the reports @h3105 and @Kiblyn11 , I will tweak the way we issue the connections to a host. 🙏

**Comment by stranger-danger-zamu** [comment] 2020-09-08 19:33
Just a heads up, I was testing this locally over wireguard (w/ a batch size of 32768, ulimit of 70k, and a timeout of 4 secs) and it worked perfectly fine. When I left it at the default timeout, it ate about half the missing ports. Running without wireguard, gave me the same result (ie. missing entries at the default timeout). So it might just be the host.

**Comment by bernardoamc** [comment] 2020-09-15 00:02
Closing this one as this varies a lot per host in terms of batch size and timeout. :)

**Closed by bernardoamc** 2020-09-15 00:02 UTC
Labels: bug
